### ISSUE TITLE
compile error 

### ISSUE THREAD

**Issue by web900621** [vueComponent/pro-layout#16]
项目在本地编译与开发的时候会得到ReferenceError: primordials is not defined 类似错误。能否提供对应的开发环境依赖呢。我想在项目上进行一些二次开发。感谢

**Comment by sendya** [comment]
node11.15 >=

**Comment by web900621** [comment]
thanks!  sucess now

**Comment by ZhongMingKun** [comment]
求最新版本的打包编译及发布npm教程

node version: 11.15.0 / 14.5.0
windows 10 64位
`yarn compile`报错
```
D:\pro-layout\node_modules\async-done\index.js:18
    throw err;
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({ uid: 3,
  name: 'js',
  branch: false,
  error:
   { PluginError: [BABEL] D:\develop\LeGeBDD\lege-fe-components\pro-layout\src\index.js: Cannot find module '@babel/plugin-syntax-jsx' (While processing: "D:\\develop\\LeGeBDD\\lege-fe-components\\pro-layout\\node_modules\\babel-plugin-transform-vue-jsx\\index.js")
       at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
       at Function.Module._load (internal/modules/cjs/loader.js:591:27)
       at Module.require (internal/modules/cjs/loader.js:723:19)
       at require (internal/modules/cjs/helpers.js:14:16)
       at module.exports (D:\develop\LeGeBDD\lege-fe-components\pro-layout\node_modules\babel-plugin-transform-vue-jsx\index.js:20:15)
       at loadDescriptor (D:\develop\LeGeBDD\lege-fe-components\pro-layout\node_modules\@ant-design-vue\tools\node_modules\@babel\core\lib\config\full.js:165:14)
       at cachedFunction (D:\develop\LeGeBDD\lege-fe-components\pro-layout\node_modules\@ant-design-vue\tools\node_modules\@babel\core\lib\config\caching.js:33:19)
       at loadPluginDescriptor (D:\develop\LeGeBDD\lege-fe-components\pro-layout\node_modules\@ant-design-vue\tools\node_modules\@babel\core\lib\config\full.js:200:28)
       at config.plugins.reduce (D:\develop\LeGeBDD\lege-fe-components\pro-layout\node_modules\@ant-design-vue\tools\node_modules\@babel\core\lib\config\full.js:69:20)
       at Array.reduce (<anonymous>)
     code: 'MODULE_NOT_FOUND',
     message:
      `[BABEL] D:\\develop\\LeGeBDD\\lege-fe-components\\pro-layout\\src\\index.js: Cannot find module '@babel/plugin-syntax-jsx' (While processing: "D:\\\\develop\\\\LeGeBDD\\\\lege-fe-components\\\\pro-layout\\\\node_modules\\\\babel-plugin-transform-vue-jsx\\\\index.js")`,
     name: 'Error',
     stack:
      `Error: [BABEL] D:\\develop\\LeGeBDD\\lege-fe-components\\pro-layout\\src\\index.js: Cannot find module '@babel/plugin-syntax-jsx' (While processing: "D:\\\\develop\\\\LeGeBDD\\\\lege-fe-components\\\\pro-layout\\\\node_modules\\\\babel-plugin-transform-vue-jsx\\\\index.js")\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:591:27)\n    at Module.require (internal/modules/cjs/loader.js:723:19)\n    at require (internal/modules/cjs/helpers.js:14:16)\n    at module.exports (D:\\develop\\LeGeBDD\\lege-fe-components\\pro-layout\\node_modules\\babel-plugin-transform-vue-jsx\\index.js:20:15)\n    at loadDescriptor (D:\\develop\\LeGeBDD\\lege-fe-components\\pro-layout\\node_modules\\@ant-design-vue\\tools\\node_modules\\@babel\\core\\lib\\config\\full.js:165:14)\n    at cachedFunction (D:\\develop\\LeGeBDD\\lege-fe-components\\pro-layout\\node_modules\\@ant-design-vue\\tools\\node_modules\\@babel\\core\\lib\\config\\caching.js:33:19)\n    at loadPluginDescriptor (D:\\develop\\LeGeBDD\\lege-fe-components\\pro-layout\\node_modules\\@ant-design-vue\\tools\\node_modules\\@babel\\core\\lib\\config\\full.js:200:28)\n    at config.plugins.reduce (D:\\develop\\LeGeBDD\\lege-fe-components\\pro-layout\\node_modules\\@ant-design-vue\\tools\\node_modules\\@babel\\core\\lib\\config\\full.js:69:20)\n    at Array.reduce (<anonymous>)`,
     __safety: undefined,
     _stack: undefined,
     plugin: 'gulp-babel',
     showProperties: false,
     showStack: false,
     fileName:
      'D:\\develop\\LeGeBDD\\lege-fe-components\\pro-layout\\src\\index.js',
     domainEmitter:
      DestroyableTransform {
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: true,
        allowHalfOpen: true,
        _transformState: [Object],
        _destroyed: false,
        _transform: [Function] },
     domainThrown: false },
  duration: [ 5, 917116401 ],
  time: 1601022651810 })
    at Gulp.emit (events.js:182:17)
    at Gulp.EventEmitter.emit (domain.js:481:20)
    at Object.error (D:\develop\LeGeBDD\lege-fe-components\pro-layout\node_modules\undertaker\lib\helpers\createExtensions.js:61:10)
    at handler (D:\develop\LeGeBDD\lege-fe-components\pro-layout\node_modules\now-and-later\lib\map.js:50:14)
    at f (D:\develop\LeGeBDD\lege-fe-components\pro-layout\node_modules\once\once.js:25:25)
    at f (D:\develop\LeGeBDD\lege-fe-components\pro-layout\node_modules\once\once.js:25:25)
    at tryCatch (D:\develop\LeGeBDD\lege-fe-components\pro-layout\node_modules\async-done\index.js:24:15)
    at done (D:\develop\LeGeBDD\lege-fe-components\pro-layout\node_modules\async-done\index.js:40:12)
    at Domain.onError (D:\develop\LeGeBDD\lege-fe-components\pro-layout\node_modules\async-done\index.js:51:5)
    at Object.onceWrapper (events.js:281:20)
error Command failed with exit code 1.
```
