### ISSUE TITLE
`vc-tools run server` Error

### ISSUE THREAD

**Issue by nuochong** [vueComponent/pro-layout#65]
执行  yarn start

然后报错
```
> Executing task: npm run start <


> @ant-design-vue/pro-layout@1.0.6 start D:\zhuniu\merge-project\test1\pro-layout
> vc-tools run server

Listening at http://localhost:9528
koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md node_modules\@ant-design-vue\tools\lib\server\index.js:43:7
D:\zhuniu\merge-project\test1\pro-layout\node_modules\@ant-design-vue\tools\node_modules\webpack\lib\webpack.js:31
                throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
                ^

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry should be an non-empty object.
   -> Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.
    at webpack (D:\zhuniu\merge-project\test1\pro-layout\node_modules\@ant-design-vue\tools\node_modules\webpack\lib\webpack.js:31:9)
    at module.exports (D:\zhuniu\merge-project\test1\pro-layout\node_modules\@ant-design-vue\tools\lib\server\index.js:65:20)
    at Object.<anonymous> (D:\zhuniu\merge-project\test1\pro-layout\node_modules\@ant-design-vue\tools\lib\cli\run.js:47:36)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\zhuniu\merge-project\test1\pro-layout\node_modules\@ant-design-vue\tools\bin\vc-tools-run.js:2:1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ant-design-vue/pro-layout@1.0.6 start: `vc-tools run server`
npm ERR! Exit status 1
npm ERR!
```
@sendya

**Comment by sendya** [comment]
本项目只是底层依赖库，不提供 start 运行支持。如果想看效果 请直接引入本库 npm，或者进入 examples 运行用例查看效果。
实在想 start 运行，请切换到 next 分支并安装好依赖后运行。
